# Generated by Django 4.1.3 on 2022-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='defult.jpg', upload_to='profile_pics'),
        ),
    ]
